/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppGenderChip: typeof import('./components/ui/AppGenderChip.vue')['default']
    AppHint: typeof import('./components/AppHint.vue')['default']
    AppImage: typeof import('./components/ui/AppImage.vue')['default']
    AppImageDropZone: typeof import('./components/ui/AppImageDropZone.vue')['default']
    AppNav: typeof import('./components/ui/AppNav.vue')['default']
    AppQuickAcess: typeof import('./components/ui/easypractice/AppQuickAcess.vue')['default']
    AppRadio: typeof import('./components/ui/AppRadio.vue')['default']
    AppRadioGroup: typeof import('./components/ui/AppRadioGroup.vue')['default']
    AppSidebar: typeof import('./components/ui/easypractice/AppSidebar.vue')['default']
    AppTextInput: typeof import('./components/ui/AppTextInput.vue')['default']
    AppTitle: typeof import('./components/ui/AppTitle.vue')['default']
    AppTopNav: typeof import('./components/ui/easypractice/AppTopNav.vue')['default']
    ColorModeSwitch: typeof import('./components/ColorModeSwitch.vue')['default']
    EasyHeaderTitle: typeof import('./components/ui/easypractice/EasyHeaderTitle.vue')['default']
    HeaderTitle: typeof import('./components/ui/easypractice/HeaderTitle.vue')['default']
    'Icon:fluent:camera16Filled': typeof import('~icons/fluent/camera16-filled')['default']
    'Icon:fluent:camera16Regular': typeof import('~icons/fluent/camera16-regular')['default']
    'Icon:fluent:delete16Filled': typeof import('~icons/fluent/delete16-filled')['default']
    'Icon:fluent:delete16Regular': typeof import('~icons/fluent/delete16-regular')['default']
    'Icon:fluent:gridDots20Filled': typeof import('~icons/fluent/grid-dots20-filled')['default']
    'Icon:fluent:navigation16Filled': typeof import('~icons/fluent/navigation16-filled')['default']
    'Icon:fluent:person16Filled': typeof import('~icons/fluent/person16-filled')['default']
    'Icon:fluent:search16Filled': typeof import('~icons/fluent/search16-filled')['default']
    'Icon:fluentic:baselineCameraAlt': typeof import('~icons/fluent/ic-baseline-camera-alt')['default']
    'Icon:ic:baselineCameraAlt': typeof import('~icons/ic/baseline-camera-alt')['default']
    'Icon:ic:baselineDelete': typeof import('~icons/ic/baseline-delete')['default']
    'Icon:ph:circlesFourBold': typeof import('~icons/ph/circles-four-bold')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    ProfileCreator: typeof import('./components/ProfileCreator.vue')['default']
    ProfileStatus: typeof import('./components/ui/ProfileStatus.vue')['default']
    ProfileView: typeof import('./components/ProfileView.vue')['default']
    Reports: typeof import('./components/ui/easypractice/reports.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarItem: typeof import('./components/ui/easypractice/SidebarItem.vue')['default']
    SidebarListItem: typeof import('./components/ui/easypractice/SidebarListItem.vue')['default']
    SideItem: typeof import('./components/ui/easypractice/SideItem.vue')['default']
    TopHeaderContext: typeof import('./components/ui/easypractice/TopHeaderContext.vue')['default']
    TopNav: typeof import('./components/ui/easypractice/TopNav.vue')['default']
    Treatments: typeof import('./components/ui/easypractice/treatments.vue')['default']
  }
}
