/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppNav: typeof import('./components/ui/AppNav.vue')['default']
    CharactorCreator: typeof import('./components/CharactorCreator.vue')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    ProfileStatus: typeof import('./components/ui/ProfileStatus.vue')['default']
    ProfileView: typeof import('./components/ProfileView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
